.TH SINDRE 1 sindre\-1.0
.SH NAME
sindre \- GUI programming language
.SH SYNOPSIS
.nh
sindre
[\fB\-f \fIprogram-file\fR]
[\fB\-e \fIprogram-text\fR]
.SH DESCRIPTION
.SS Overview
Sindre is a programming language inspired by Awk that makes it easy to
write simple graphical programs in the spirit of dzen, dmenu, xmobar,
gsmenu and the like.
.SS Options
.TP
.PD 0
.BI \-f " program-file"
.TP
.PD
.BI \-\^\-file " program-file"
Read the program source from the file
.IR program-file .
Multiple
.B \-f
options may be used, and may be interleaved with
.B \-e
options.  See the section on
.B Code Substitution
below.
.TP
.PD 0
.BI \-e " program-text"
.TP
.PD
.BI \-\^\-expression " program-text"
Read the program source from the argument
.IR program-text .
Multiple
.B \-e
options may be used, and may be interleaved with
.B \-f
options.  See the section on
.B Code Substitution
below.
.SH USAGE
.SS Code Substitution
When multiple
.B \-f
and
.B \-e
options are used, Sindre conceptually concatenates the given program
text in the order of the options.  There are two differences from
plain concatenation, however:
.TP
.B Duplicate definitions
A piece of Sindre program text is normally not allowed to define two
global variables or functions with the same name, nor to contain two
GUI blocks.  When the above options are used, redefinitions of
previous definitions appearing later in the option list take
precedence.
.TP
.B Event handling priority
Event handlers are run from top to bottom in terms of the program
text, but event handlers in code appearing later in the option list
are run first.  Thus,

.ft B
        sindre -e 'obj->ev() { print "foo" }
                   obj->ev() { print "bar" }'
               -e 'obj->ev() { print "baz" }'
.ft R

will print "baz foo bar" whenever the event
.B obj->ev()
happens.  BEGIN blocks are similarly executed in reverse order.

.ft B
        sindre -e 'BEGIN { print "I go last" }'
               -e 'BEGIN { print "I go first" }'
.ft R

.SH EXIT STATUS
Sindre returns a
.B 0
exit status on success, and
.B 1
if there was an internal problem.
.SH SEE ALSO
.BR dmenu (1), awk (1)
