#!/bin/bash
code=$(cat <<EOF
GUI { Vertically { dial=Dial(max=physmax);
                   label=Label(label=labelstring) } }
option min (,--min,"Minimum value of the dial", "INTEGER", 0)
option max (,--max,"Maximum value of the dial", "INTEGER", 12)
option labelstring(,--label,"Text of label below the dial", "STRING", "")
physmax=max-min;
stdin->lines(lines) { dial.value = lines; }
<Escape> || <Enter> || <C-g> { exit 0; }
BEGIN { focus dial; }
EOF
)
exec -a dial sindre -e "$code" "$@"
