#!/bin/bash
gui=$(cat <<EOF
GUI {
Horizontally@bottom?"bot":"top" {
    prompt=Label(label=pstring,highlight=1);
    input=Input(minwidth=200);
    list=HList();
  }
}
EOF
)
for arg in "$@"; do
if [ "$arg" = '-l' ]; then
    gui=$(cat <<EOF
GUI {
Horizontally@bottom?"bot":"top" {
  Vertically {
    prompt=Label(label=pstring,highlight=1);
    Blank;
  }
  Vertically {
    input=Input(minwidth=0);
    list=VList(lines=lines);
  }
}
}
option lines (-l,,"List items vertically, with the given number of lines.", "INTEGER", 10)
EOF
    )
fi
done
code=$(cat <<EOF
BEGIN { input.value = contents }
option pstring (-p,--prompt,"Set the input prompt", "STRING", "")
option bottom (-b,,"Appear at bottom of screen")
option contents(-c,,"Starting contents of buffer", "STRING", "")
function complete() { if (list.selected) { input.value = list.selected } }
function filter() { list.filter(input.value) }
function select() { print input.value; exit }
function quit() { exit 1 }
stdin->lines(lines) { list.insert(lines) }
BEGIN { focus input }
<C-g> { quit() }
<Up> || <C-p> { list.prev() }
<Down> || <C-n> { list.next() }
<Return> { complete(); select(); }
<Shift-Return> { select(); }
<C-i> || <Tab> { complete() }
input.value->changed(from, to) { filter() }
EOF
)
exec -a dmenu sindre -e "$gui" -e "$code" "$@"
