#!/bin/bash
code=$(cat <<EOF
GUI {
Horizontally@"top" {
    prompt=Label(label=pstring,highlight=1);
    input=Input(minwidth=200);
    list=List();
  }
}
option pstring (-p,--prompt,"Set the input prompt", "STRING", "")
stdin->contents(data) { list.insert(data) }
BEGIN { focus input }
<C-g> { exit 1 }
<Right> { list.next() }
<Left> { list.prev() }
<Return> { print list.selected || input.value; exit }
<Shift-Return> { print input.value; exit }
<C-i> { if (list.selected) { input.value = list.selected } }
input.value->changed(from, to) { list.filter(to) }
EOF
)
exec -a dmenu sindre -e "$code" "$@"
