#!/bin/sh
gui() {
    code=$(cat <<EOF
input->changed(from, to) {
  list.clear();
  list.insert(filename);
  print substr(to, 0, match(to, "/[^/]*$"));
}
function complete() {
  if (list.selected) {
    input.value = substr(input.value, 0, match(input.value, "[^/]*$")-1) list.selected
  }
}
BEGIN { list.insert(filename); }
function filter() { list.filter(substr(input.value, match(input.value, "[^/]*$"), RLENGTH)); }
function quit() { print; exit }
option filename(,--filename,"Default filename if a directory is selected", "filename");
EOF
    )
    dir=$(mktemp -p "${TMPDIR:-/tmp}" -d dir-XXXXXX) || exit 1
    fifo=$dir/fifo
    mkfifo "$fifo" || { rmdir "$dir"; exit 1; }
    ls -A -F | sinmenu -l 10 -e "$code" -p File: -c $PWD/ "$@" < $fifo |\
while read line; do
    echo $line 1>&3
    ls -A -F /"$line" 2>/dev/null | sed 's/\*$//'
    done 3>&1 1>$fifo | tail -n 1 | sed '/^$/d'
    rm $fifo
    rmdir $dir
}

ret=$(gui "$@")

[ -z "$ret" ] && exit 1 || echo "$ret"
