#!/bin/bash
code=$(cat <<EOF
GUI {
Horizontally@bottom?"bot":"top" {
  Vertically {
    prompt=Label(label=pstring,highlight=1);
    Blank;
  }
  Vertically {
    input=Input(minwidth=0);
    list=VList();
  }
}
}
EOF
)
exec -a vdmenu $(dirname "$0")/dmenu -e "$code" "$@"
